### ISSUE TITLE
[System] won't play audio when rendering actor sheets in Simple Worldbuilding (wrong hooks I think)

### ISSUE THREAD

**Issue by EsotericOdyssey** [SalieriC/immersive-render#3]
what it says in the title, idk if this is just the case with Simple Worldbuilding or if this is a mistake on your part, but it appears to be looking for the "renderCharacterSheet" hook to play audio for opening an actor's sheet when (in SWB at least) there's only a "renderActorSheet" hook. works fine for items and journals just fine though.

**Comment by SalieriC** [comment]
I am planning a framework for different systems users can easily contribute to. FVTT has far too many systems for me to cover so I'll have to rely on the community to cover them. Sorry about that. I am trying to get this framework done asap but no promises.

**Comment by SalieriC** [comment]
Done in Git. Thanks again for your help. =)
